#docker build -t base_compilar_pilgor -f docker_base .

version: '3'

services:
  my-service:
    image: base_compilar_pilgor:latest
    volumes:
      - .:/workspace  # Mounts the current directory inside the container as /workspace
    command: >
      bash -c '
        cd /workspace/src &&
        ghc cargaKD.hs -static -O2 -outputdir ./compil_files &&
        ghc simulacion.hs -static -O2 -outputdir ./compil_files &&
        mv cargaKD simulacion ../tmp &&
        cd .. &&
        cd ./tmp
      '
    stop_signal: SIGINT